### ISSUE TITLE
Possible incorrect information in Apple Unified Logging and Activity Tracing formats working document

### ISSUE THREAD

**Issue by SammyB428** [libyal/dtformats#12]
Section 2.3, the fields beginning with Sub chunk tag 0x6102 are off by 12 bytes. The Hardware model string field begins at offset 104 and is 32 bytes wide. The next field should begin at offset 136 (104+32) but the documentation says the offset is 124. I verified with a tracev3 file and it should be 136. Perhaps you were thinking in hex? 32 == x20, 104 + x20 == 124? ;-)

**Comment by SammyB428** [comment]
DOH! Just noticed that the structure size should be 224, not 208.

**Comment by joachimmetz** [comment]
@SammyB428 can you submit a PR, with example files, this project contains a lot of WIP documents

**Comment by joachimmetz** [comment]
Also being more specific about your version of the tracev3 file could be beneficial. Random claims not backed up by data are going to be ignored
