### ISSUE TITLE
Timesync in unified_logging

### ISSUE THREAD

**Issue by Schramp** [libyal/dtformats#27]
Hello Joachim, 

I think you should round at the early stage of calculating te timebase.
Had some differences comparing to the old output.

Best regards,

Ruud 

```
@@ -4164,7 +4170,7 @@ class TraceV3File(data_format.BinaryDataFile):
 
     if self._timesync_boot_record:
       self._timesync_timebase = (
-          self._timesync_boot_record.timebase_numerator //
+          self._timesync_boot_record.timebase_numerator /
           self._timesync_boot_record.timebase_denominator)
 


--- a/dtformats/unified_logging.py
+++ b/dtformats/unified_logging.py
@@ -2834,12 +2834,12 @@ class TraceV3File(data_format.BinaryDataFile):
     timesync_record = self._GetTimesyncRecord(continuous_time)
     if timesync_record:
       continuous_time -= timesync_record.kernel_time
-      timestamp = timesync_record.timestamp + (
-          continuous_time * self._timesync_timebase)
+      timestamp = int(timesync_record.timestamp + (
+          continuous_time * self._timesync_timebase))
 
     elif self._timesync_boot_record:
-      timestamp = self._timesync_boot_record.timestamp + (
-          continuous_time * self._timesync_timebase)
+      timestamp = int(self._timesync_boot_record.timestamp + (
+          continuous_time * self._timesync_timebase))
 
```

**Comment by joachimmetz** [comment]
> Had some differences comparing to the old output.

what old output?

I compared it against the output of the MacOS log tools for at least a couple of test cases and they match?

what rounding issues are you seeing?

**Comment by Schramp** [comment]
I am comparing against the output of my fork of UnifiedLogReader https://github.com/Schramp/UnifiedLogReader

In november 2022 I compared the output of that fork with tooling of MacOS  (Unfortunately my Mac workstation is in storage for a few days, because we'r getting new desks), so admittedly my comparison is currently not a good ground truth. That comparison lead the the commit: https://github.com/Schramp/UnifiedLogReader/commit/0b73681f5fb945be650b2ca1ecb22c6fa2f544a5 

This commit uses the denom/nom as a float. 

In integer math  (delta_continuous_time*denom)/nominator <> delta_continuous_time*(denom/nominator)

The later expression has a rounding error on the division (and the earlier possibly a integer overflow, but normaly not in python). In my experiment in november 2022 I did the math in floating point to get accurate timestamps.

The provided patch changes the integer division to a floating point division (storing a floating point in _timesync_timebase), to make sure timestamp is an integer again a typecast was added there.

**Comment by Schramp** [comment]
Just checked that https://github.com/mandiant/macos-UnifiedLogs agrees with my calculation as well (still no ground truth, sorry)

**Comment by joachimmetz** [comment]
I'll have a closer look, agree with delaying the ceil/floor to as late as possible. Maybe fixed point might be an alternative. Do you know if the MacOS log code uses a floor or ceil ?

**Comment by joachimmetz** [comment]
> That comparison lead the the commit: Schramp/UnifiedLogReader@0b73681

it looks like this introduces time base correction (in general)

**Comment by joachimmetz** [comment]
> The later expression has a rounding error on the division (and the earlier possibly a integer overflow, but normaly not in python)

for native Python int we don't have to be worried of it overflowing, the one thing that might cause a rounding difference (would not necessarily call it an error) would be a different of ceil/floor and loss of precision due to early rounding

**Comment by Schramp** [comment]
The difference in rounding results in errors in the order of minutes. In traffic accident analyses the focus is on seconds (e.g. ECLI:NL:RBMNE:2022:2902)

**Comment by joachimmetz** [comment]
> The difference in rounding results in errors in the order of minutes.

interesting any context on the actual rounding error in this case? for timesync I've noticed that the method of determining which timesync record applies is also not documented, since it can be that no timesync record exists

**Comment by joachimmetz** [comment]
>  There is a case in NL where it is discussed to level of tens of seconds, but that is not this case.

Would be interested if you have a reference. Seeing the granularity of the timestamps don't think the error will be that large in this case, also the Mac OS log tool seems to vary between seconds and microseconds in its representation of the date and time values.

Maybe some related references:

* https://osdfir.blogspot.com/2020/09/testing-digital-forensic-data.html
* https://osdfir.blogspot.com/2021/10/pearls-and-pitfalls-of-timeline-analysis.html

**Comment by joachimmetz** [comment]
Changes, merged. Thanks for flagging. Will add some information to the documentation as well, along the line.

**Comment by Schramp** [comment]
Thanks.
